   [theme]
   base = "light"
   primaryColor = "#4a3aa7"
   backgroundColor = "#ffffff"
   secondaryBackgroundColor = "#f6f7f5"
   textColor = "#0b0b0b"
   font = "sans serif"

   [client]
   toolbarMode = "minimal"

   [browser]
   gatherUsageStats = false
